name: detakapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  intl: 0.17.0
  get: 4.6.3
  get_storage: 2.0.3
  connectivity_plus: 2.3.0
  permission_handler: 9.2.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.2
  smooth_page_indicator: ^1.0.0+2
  youtube_player_iframe: ^2.3.0
  flutter_native_splash: ^2.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  color: "#fe7272"
  image: assets/images/splashLogo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    # - assets/models/
  uses-material-design: true

