name: detakapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  geolocator: 8.2.1
  geocoding: 2.0.4
  permission_handler: 9.2.0
  connectivity_plus: 2.3.0
  get_storage: 2.0.3
  flutter: 
    sdk: flutter
  google_fonts: ^2.3.2
  smooth_page_indicator: ^1.0.0+2
  youtube_player_flutter: ^8.1.0
  youtube_player_iframe: ^2.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    # - assets/models/
  uses-material-design: true

