name: detakapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  intl: 0.17.0
  get: 4.6.3
  get_storage: 2.0.3
  connectivity_plus: 2.3.0
  permission_handler: 9.2.0
  cupertino_icons: ^1.0.2
  
  # Google fonts
  google_fonts: ^2.3.2
  
  # Smooth indicator
  smooth_page_indicator: ^1.0.0+2
  
  # Youtube player
  youtube_player_iframe: ^2.3.0
  
  # Splashscreen
  flutter_native_splash: ^2.2.1
  
  # Loading shimmer
  shimmer: ^2.0.0

  # HTML reader
  flutter_widget_from_html: ^0.8.5
  
  # Video PLayerch
  video_player: ^2.4.0
  chewie: ^1.3.3
  
  wakelock: ^0.6.1+2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  color: "#fe7272"
  image: assets/images/splashLogo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/
    # - assets/models/
  uses-material-design: true

